compressionLevel: mixed

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.9.2.cjs

packageExtensions:
  cypress@*:
    dependencies:
      "@types/node": "*"
    peerDependencies:
      "@types/node": "*"
