compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  cypress@*:
    dependencies:
      "@types/node": "*"
    peerDependencies:
      "@types/node": "*"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
